"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { createClient } from "../../lib/supabase/browser";

type Clip={id:string;title:string;category:string;description:string;src:string|null;emoji:string;tags:string[]};
const seed:Clip[]=[
{id:"dance-1",title:"Dança no rooftop",category:"Dança",description:"Cidade • vertical 9:16",src:"https://videos.pexels.com/video-files/16120732/16120732-uhd_2160_3840_30fps.mp4",emoji:"💃",tags:["dança","viral"]},
{id:"dance-2",title:"Dança viral urbana",category:"Dança",description:"Urbano • vertical 9:16",src:"https://videos.pexels.com/video-files/7571002/7571002-uhd_2160_4096_25fps.mp4",emoji:"🕺",tags:["dança"]},
{id:"soccer-1",title:"Gol incrível",category:"Futebol",description:"Esporte • comemoração",src:"https://videos.pexels.com/video-files/3195394/3195394-hd_1920_1080_25fps.mp4",emoji:"⚽",tags:["futebol","esporte"]},
{id:"soccer-2",title:"Treino de futebol",category:"Futebol",description:"Esporte • treino",src:"https://videos.pexels.com/video-files/3196296/3196296-hd_1920_1080_25fps.mp4",emoji:"🥅",tags:["futebol"]},
{id:"action-1",title:"Ação urbana",category:"Ação",description:"Cidade • movimento",src:"https://videos.pexels.com/video-files/5873605/5873605-uhd_2160_3840_24fps.mp4",emoji:"🏙️",tags:["ação"]},
{id:"action-2",title:"Aventura e natureza",category:"Ação",description:"Aventura • exterior",src:"https://videos.pexels.com/video-files/4188339/4188339-uhd_4096_2160_24fps.mp4",emoji:"🌴",tags:["ação","aventura"]},
{id:"music-1",title:"Show ao vivo",category:"Música",description:"Palco • performance",src:"https://videos.pexels.com/video-files/7646456/7646456-uhd_2160_3840_25fps.mp4",emoji:"🎤",tags:["música"]},
{id:"comedy-1",title:"Performance absurda",category:"Comédia",description:"Viral • humor",src:"https://videos.pexels.com/video-files/7005842/7005842-hd_1280_720_24fps.mp4",emoji:"😂",tags:["comédia","viral"]},
{id:"comedy-2",title:"Viagem inesperada",category:"Comédia",description:"Reação • humor",src:"https://videos.pexels.com/video-files/5519762/5519762-uhd_3840_2160_30fps.mp4",emoji:"🌎",tags:["comédia"]},
{id:"fashion-1",title:"Fashion em movimento",category:"Elegante",description:"Editorial • moda",src:"https://videos.pexels.com/video-files/9512048/9512048-uhd_2160_4096_25fps.mp4",emoji:"✨",tags:["elegante","moda"]},
{id:"car-1",title:"Carro e estrada",category:"Ação",description:"Carro • viagem",src:"https://videos.pexels.com/video-files/857267/857267-hd_1920_1080_24fps.mp4",emoji:"🚗",tags:["carro","ação"]},
{id:"dance-3",title:"Dança com carro esportivo",category:"Dança",description:"Dança • carro • viral",src:"https://videos.pexels.com/video-files/16120734/16120734-uhd_2160_3840_30fps.mp4",emoji:"🏎️",tags:["dança","carro"]},
];
function ClipCard({clip,selected,onSelect}:{clip:Clip;selected:boolean;onSelect:(c:Clip)=>void}){
 const [failed,setFailed]=useState(!clip.src);
 return <article className="video-card video-motion viral-video-card" style={{position:"relative",minHeight:340,overflow:"hidden"}}>
  {!failed&&clip.src?<video src={clip.src} muted loop playsInline preload="metadata" onError={()=>setFailed(true)} style={{width:"100%",height:"100%",position:"absolute",inset:0,objectFit:"cover"}}/>:
   <div className="video-fallback" style={{position:"absolute",inset:0,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",gap:12,background:"radial-gradient(ellipse at top,#26345a,#080a14 70%)",color:"white"}}><span style={{fontSize:56}}>{clip.emoji}</span><b>{clip.title}</b><small>Prévia indisponível — escolha outro clipe ou envie o seu</small></div>}
  <div className="video-overlay" style={{position:"absolute",inset:"auto 0 0",zIndex:1}}><div className="video-copy"><b>{clip.emoji} {clip.title}</b><small>{clip.description}</small><small>{clip.category}</small></div><button className="video-buy" onClick={()=>onSelect(clip)}>{selected?"✓ Selecionado":"Selecionar vídeo"}</button></div>
 </article>
}
export default function Videos(){
 const [clips,setClips]=useState<Clip[]>(seed),[filter,setFilter]=useState("Todos"),[selected,setSelected]=useState(""),[tab,setTab]=useState("biblioteca"),[msg,setMsg]=useState(""),[file,setFile]=useState<File|null>(null),[customUrl,setCustomUrl]=useState("");
 useEffect(()=>{(async()=>{try{const saved=localStorage.getItem("avatar-studio-selected-video");if(saved)setSelected(JSON.parse(saved).id||"");const sb=createClient();const {data}=await sb.from("video_templates").select("id,name,description,video_url,thumbnail_url,style,tags").eq("active",true).order("sort_order");if(data?.length){const fromDb:Clip[]=data.filter((x:any)=>x.video_url||x.thumbnail_url).map((x:any)=>({id:x.id,title:x.name,category:category(x.style,x.tags),description:x.description||"Vídeo de referência",src:x.video_url||x.thumbnail_url,emoji:emoji(category(x.style,x.tags)),tags:x.tags||[]}));if(fromDb.length)setClips(fromDb)}}catch{}})()},[]);
 function choose(c:Clip){const payload={id:c.id,title:c.title,category:c.category,src:c.src,selectedAt:new Date().toISOString()};try{localStorage.setItem("avatar-studio-selected-video",JSON.stringify(payload));setSelected(c.id);setMsg("Referência selecionada. Para iniciar uma transformação real, é necessário escolher um avatar e conectar um provedor de vídeo por IA; esta seleção ainda não gera o vídeo final.")}catch{setMsg("Não foi possível guardar a seleção neste navegador.")}}
 function category(style:string,tags:string[]=[]){const s=(style+" "+tags.join(" ")).toLowerCase();if(s.includes("futebol")||s.includes("soccer"))return "Futebol";if(s.includes("dan"))return "Dança";if(s.includes("mús")||s.includes("music"))return "Música";if(s.includes("com")||s.includes("viral")||s.includes("random"))return "Comédia";if(s.includes("fashion")||s.includes("lux"))return "Elegante";if(s.includes("ação")||s.includes("avent")||s.includes("carro"))return "Ação";return "Outro"}
 function emoji(c:string){return ({Dança:"💃",Futebol:"⚽",Música:"🎤",Comédia:"😂",Elegante:"✨",Ação:"🎬",Outro:"🎞️"} as Record<string,string>)[c]||"🎬"}
 async function upload(){if(!file)return;if(!file.type.startsWith("video/")){setMsg("Escolha um arquivo de vídeo válido.");return}if(file.size>100*1024*1024){setMsg("O arquivo deve ter até 100 MB.");return}const url=URL.createObjectURL(file);setCustomUrl(url);const c:Clip={id:"upload-"+file.name,title:file.name,category:"Meu vídeo",description:"Arquivo local • referência",src:url,emoji:"📤",tags:["upload"]};setClips(p=>[c,...p]);setSelected(c.id);try{localStorage.setItem("avatar-studio-selected-video",JSON.stringify({id:c.id,title:c.title,category:c.category,src:"",custom:true,selectedAt:new Date().toISOString()}))}catch{}setMsg("Arquivo pronto para prévia local. Ele ainda não foi enviado ao servidor nem processado pela IA; não feche esta página se quiser manter a prévia.")}
 const filters=["Todos","Comédia","Dança","Futebol","Ação","Música","Elegante","Outro"];
 const shown=clips.filter(c=>filter==="Todos"||c.category===filter);
 return <main className="library-shell"><nav className="profile-nav"><Link className="brand-logo-link" href="/"><img src="/logo.svg" alt="Avatar Studio AI" style={{width:180}}/></Link><div><Link href="/studio">Meu perfil</Link><Link href="/avatars">Avatares</Link><Link href="/studio/planos">Planos</Link></div></nav>
 <section className="library-head"><div className="section-kicker">🎬 BIBLIOTECA DE VÍDEOS</div><h1>Escolha a referência para seu próximo vídeo.</h1><p>Clipes de comédia, dança, futebol, ação, música e moda. As prévias com links quebrados mostram uma alternativa em vez de uma tela preta.</p><div className="filter-pills">{["biblioteca","incluir"].map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t==="biblioteca"?"🎞️ Biblioteca":"📤 Incluir meu vídeo"}</button>)}</div></section>
 {tab==="biblioteca"?<><section className="library-head" style={{paddingTop:8}}><div className="filter-pills">{filters.map(f=><button key={f} className={filter===f?"active":""} onClick={()=>setFilter(f)}>{f}</button>)}</div>{msg&&<p className="video-audio-note" role="status">{msg}</p>}</section><section className="video-library-grid">{shown.map(c=><ClipCard key={c.id} clip={c} selected={selected===c.id} onSelect={choose}/>)}</section></>:<section className="creator-shell"><div className="section-kicker">📤 VÍDEO DE REFERÊNCIA</div><h2>Inclua seu próprio vídeo</h2><p>Escolha um vídeo de até 100 MB para pré-visualizar. O envio ao servidor e a transformação por IA ainda não estão conectados.</p><label>Arquivo de vídeo<input type="file" accept="video/*" onChange={e=>setFile(e.target.files?.[0]||null)} style={{display:"block",marginTop:12}}/></label>{file&&<p>{file.name} • {(file.size/1024/1024).toFixed(1)} MB</p>}<button className="hero-primary" disabled={!file} onClick={upload}>Pré-visualizar e selecionar</button>{customUrl&&<video src={customUrl} controls playsInline style={{display:"block",width:"min(100%,420px)",marginTop:20,borderRadius:16}}/>}{msg&&<p role="status">{msg}</p>}</section>}
 </main>
}