"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { createClient } from "../../../lib/supabase/browser";

export default function NovoAvatar(){
 const [user,setUser]=useState<any>(null); const [form,setForm]=useState({name:"O Rei do Caos",gender:"Masculino",hair:"Bowl Cut",hair_color:"Verde",body_type:"Musculoso",clothing:"terno minúsculo roxo, gravata gigante e tênis laranja",style:"Engraçado",scene:"mercado futurista",prompt:"Personagem absurdamente engraçado, expressão dramática, pose inesperada, fotografia editorial realista, composição vertical 9:16"}); const [msg,setMsg]=useState(""); const [loading,setLoading]=useState(false); const [limit,setLimit]=useState(false);
 useEffect(()=>{(async()=>{const {data:{user}}=await createClient().auth.getUser();if(!user){window.location.href="/login?next=/studio/avatar-novo";return;}setUser(user)})()},[]);
 const set=(k:string,v:string)=>setForm(x=>({...x,[k]:v}));
 const surprise=()=>{const pick=(a:string[])=>a[Math.floor(Math.random()*a.length)];setForm(x=>({...x,name:pick(["O Rei do Caos","Tia do Multiverso","CEO do Pastel","Doutor Penteado","Barão do Pagode","Musa do Apocalipse"]),gender:pick(["Feminino","Masculino","Não binário"]),hair:pick(["Bowl Cut","Geométrico","Buzz Cut","Cacheado Curto","Assimétrico","Raspado","Moicano torto"]),hair_color:pick(["Platinum","Rosa choque","Azul elétrico","Vermelho","Roxo","Verde neon","Laranja","Prata"]),body_type:pick(["Normal","Forte","Plus-size","Musculoso","Muito musculoso"]),clothing:pick(["terno minúsculo com gravata gigante","jaqueta metalizada e bermuda floral","roupão de luxo com chinelo","uniforme espacial com pochete","look de gala com botas de borracha","camisa estampada e capa dramática"]),style:pick(["Engraçado","Street","Cyber","Luxo","Retrô","Futurista"]),scene:pick(["mercado futurista","praia em dia de tempestade","elevador dourado","academia intergaláctica","rooftop neon","salão de beleza cyberpunk"]),prompt:"Personagem memorável e cômico, expressão exagerada, pose inesperada, visual editorial fotorrealista, luz cinematográfica, enquadramento vertical 9:16"}))};
 async function createAvatar(e:React.FormEvent){e.preventDefault();setLoading(true);setMsg("");setLimit(false);try{const sb=createClient();const {data,error}=await sb.from("avatars").insert({user_id:user.id,name:form.name.trim()||"Meu Avatar",source_type:"digital",gender:form.gender,style:form.style,clothing:form.clothing,scene:form.scene,status:"draft",safety_status:"pending",appearance_config:form}).select("id").single();if(error)throw error;setMsg("Avatar criado no seu Studio. A próxima etapa de geração visual pode usar essa configuração.");setForm(x=>({...x,name:"Meu Avatar",prompt:""}));}catch(e){const m=e instanceof Error?e.message:"Não foi possível criar o avatar.";setMsg(m);if(m.includes("AVATAR_LIMIT_REACHED")||m.includes("Limite de avatares"))setLimit(true)}finally{setLoading(false)}}
 return <main className="library-shell"><nav className="profile-nav"><Link className="brand-mark" href="/"><span className="brand-icon">✦</span> AVATAR STUDIO <b>AI</b></Link><div><Link href="/avatars">Avatares</Link><Link href="/videos">Vídeos</Link><Link href="/studio">Meu perfil</Link></div></nav><section className="creator-shell"><div className="section-kicker">✨ CRIAR AVATAR</div><h1>Monte seu personagem.</h1><p>Crie figuras impossíveis de ignorar: cortes estranhos, cores elétricas, roupas absurdas e personalidade de meme. A configuração fica salva no seu perfil.</p><button type="button" className="hero-secondary creator-buy" onClick={surprise}>🎲 Surpreenda-me com um personagem absurdo</button><form className="creator-form" onSubmit={createAvatar}><label>Nome<input value={form.name} onChange={e=>set("name",e.target.value)} required/></label><label>Gênero<select value={form.gender} onChange={e=>set("gender",e.target.value)}><option value="">Não definir</option><option>Feminino</option><option>Masculino</option><option>Não binário</option></select></label><label>Cabelo<select value={form.hair} onChange={e=>set("hair",e.target.value)}>{["Bowl Cut","Curto","Geométrico","Buzz Cut","Cacheado Curto","Assimétrico","Raspado","Moicano torto","Franja reta exagerada"].map(x=><option key={x}>{x}</option>)}</select></label><label>Cor do cabelo<select value={form.hair_color} onChange={e=>set("hair_color",e.target.value)}>{["Platinum","Rosa","Rosa choque","Azul","Azul elétrico","Vermelho","Roxo","Verde","Verde neon","Laranja","Preto","Prata","Loiro"].map(x=><option key={x}>{x}</option>)}</select></label><label>Corpo<select value={form.body_type} onChange={e=>set("body_type",e.target.value)}>{["Normal","Forte","Plus-size","Musculoso"].map(x=><option key={x}>{x}</option>)}</select></label><label>Estilo<select value={form.style} onChange={e=>set("style",e.target.value)}>{["Editorial","Street","Fashion","Cyber","Luxo","Esportivo","Executivo","Retrô","Futurista","Engraçado","Comédia absurda","Meme cinematográfico"].map(x=><option key={x}>{x}</option>)}</select></label><label>Roupa<input value={form.clothing} onChange={e=>set("clothing",e.target.value)} placeholder="Ex.: polo azul curta + calça marrom larga"/></label><label>Cenário<input value={form.scene} onChange={e=>set("scene",e.target.value)} placeholder="Ex.: rooftop de cidade"/></label><label className="creator-wide">Prompt livre<textarea value={form.prompt} onChange={e=>set("prompt",e.target.value)} placeholder="Descreva exatamente o personagem que você quer…"/></label><button className="hero-primary creator-submit" disabled={loading}>{loading?"Salvando…":"Criar meu avatar →"}</button></form>{msg&&<p className="form-msg credit-message">{msg}</p>}{limit&&<Link href="/studio/creditos" className="hero-secondary creator-buy">Comprar +1 avatar por R$ 5 →</Link>}</section></main>
}
