"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { createClient } from "../../../lib/supabase/browser";

export default function NovoAvatar(){
 const [user,setUser]=useState<any>(null); const [form,setForm]=useState({name:"Meu Avatar",gender:"",hair:"Bowl Cut",hair_color:"Platinum",body_type:"Forte",clothing:"",style:"Editorial",scene:"Estúdio",prompt:""}); const [msg,setMsg]=useState(""); const [loading,setLoading]=useState(false); const [limit,setLimit]=useState(false);
 useEffect(()=>{(async()=>{const {data:{user}}=await createClient().auth.getUser();if(!user){window.location.href="/login?next=/studio/avatar-novo";return;}setUser(user)})()},[]);
 const set=(k:string,v:string)=>setForm(x=>({...x,[k]:v}));
 async function createAvatar(e:React.FormEvent){e.preventDefault();setLoading(true);setMsg("");setLimit(false);try{const sb=createClient();const {data,error}=await sb.from("avatars").insert({user_id:user.id,name:form.name.trim()||"Meu Avatar",source_type:"digital",gender:form.gender,style:form.style,clothing:form.clothing,scene:form.scene,status:"draft",safety_status:"pending",appearance_config:form}).select("id").single();if(error)throw error;setMsg("Avatar criado no seu Studio. A próxima etapa de geração visual pode usar essa configuração.");setForm(x=>({...x,name:"Meu Avatar",prompt:""}));}catch(e){const m=e instanceof Error?e.message:"Não foi possível criar o avatar.";setMsg(m);if(m.includes("AVATAR_LIMIT_REACHED")||m.includes("Limite de avatares"))setLimit(true)}finally{setLoading(false)}}
 return <main className="library-shell"><nav className="profile-nav"><Link className="brand-mark" href="/"><span className="brand-icon">✦</span> AVATAR STUDIO <b>AI</b></Link><div><Link href="/avatars">Avatares</Link><Link href="/videos">Vídeos</Link><Link href="/studio">Meu perfil</Link></div></nav><section className="creator-shell"><div className="section-kicker">✨ CRIAR AVATAR</div><h1>Monte seu personagem.</h1><p>Escolha cabelo, corpo, roupa, estilo e cenário. A configuração fica salva no seu perfil.</p><form className="creator-form" onSubmit={createAvatar}><label>Nome<input value={form.name} onChange={e=>set("name",e.target.value)} required/></label><label>Gênero<select value={form.gender} onChange={e=>set("gender",e.target.value)}><option value="">Não definir</option><option>Feminino</option><option>Masculino</option><option>Não binário</option></select></label><label>Cabelo<select value={form.hair} onChange={e=>set("hair",e.target.value)}>{["Bowl Cut","Curto","Geométrico","Buzz Cut","Cacheado Curto","Assimétrico","Raspado"].map(x=><option key={x}>{x}</option>)}</select></label><label>Cor do cabelo<select value={form.hair_color} onChange={e=>set("hair_color",e.target.value)}>{["Platinum","Rosa","Azul","Vermelho","Roxo","Verde","Laranja","Preto","Prata","Loiro"].map(x=><option key={x}>{x}</option>)}</select></label><label>Corpo<select value={form.body_type} onChange={e=>set("body_type",e.target.value)}>{["Normal","Forte","Plus-size","Musculoso"].map(x=><option key={x}>{x}</option>)}</select></label><label>Estilo<select value={form.style} onChange={e=>set("style",e.target.value)}>{["Editorial","Street","Fashion","Cyber","Luxo","Esportivo","Executivo","Retrô","Futurista","Engraçado"].map(x=><option key={x}>{x}</option>)}</select></label><label>Roupa<input value={form.clothing} onChange={e=>set("clothing",e.target.value)} placeholder="Ex.: polo azul curta + calça marrom larga"/></label><label>Cenário<input value={form.scene} onChange={e=>set("scene",e.target.value)} placeholder="Ex.: rooftop de cidade"/></label><label className="creator-wide">Prompt livre<textarea value={form.prompt} onChange={e=>set("prompt",e.target.value)} placeholder="Descreva exatamente o personagem que você quer…"/></label><button className="hero-primary creator-submit" disabled={loading}>{loading?"Salvando…":"Criar meu avatar →"}</button></form>{msg&&<p className="form-msg credit-message">{msg}</p>}{limit&&<Link href="/studio/creditos" className="hero-secondary creator-buy">Comprar +1 avatar por R$ 5 →</Link>}</section></main>
}
